### PR TITLE
Prevent caching of buffer commentstring

### LINKED ISSUE #477: `commentstring` value is not updated after first usage in the buffer
[suy/vim-context-commentstring](https://github.com/suy/vim-context-commentstring) fixes the issue of **Lue in VimScript** and [this issue of **HTML**](https://github.com/preservim/nerdcommenter/issues/17) by changing the `commentstring` value, but another issue appeared after using this, I think **nerdcommenter** stores the first use of `commentstring` in the current buffer and never read it again:

https://user-images.githubusercontent.com/42011920/129219251-a0862097-5831-4f09-960b-e1a070a43999.mp4

_Originally posted by @MuhammadSawalhy in https://github.com/preservim/nerdcommenter/issues/17#issuecomment-897709359_

### PR DESCRIPTION
**Pull request by ppwwyyxx**
Fix #477

### CODE REVIEW

**Review by alerque — APPROVED** [review]

**Comment by alerque** [comment]
Thanks for taking the time to contribute!

**Comment by alerque** [comment]
I had to revert this change. I think I understand what you were trying to fix but it completely blew up the plugin so it didn't work at all for my setup. I reverted it so people wouldn't run into the same total breakage. Can we look into what that was about?

**Comment by ppwwyyxx** [comment]
This works in my setup. How do I reproduce the breakage so I can look into it?

**Comment by ppwwyyxx** [comment]
I did notice one potential issue of infinite recursion. It's fixed here https://github.com/preservim/nerdcommenter/commit/a3e82853089e0f7a14c3475ec997f1aa371f4210 but I'm not sure if that's the breakage you're seeing.

**Comment by alerque** [comment]
That commit you linked seems to fix the issue I was having with it. Can you submit that as a new PR?

**Pull request merged**
